default_language_version:
    python: python3.11

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ["--maxkb=1000"]
    -   id: check-shebang-scripts-are-executable
    -   id: detect-private-key

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        exclude: 'migrations/.*'

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        exclude: 'migrations/.*'
        args: ["--profile", "black", "--filter-files"]


- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.1.6'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format
      exclude: 'migrations/.*'
