version: "3.9"

services:
  db:
    image: postgres:15.2
    container_name: postgres
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  app:
    container_name: django
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    command: >
      /bin/bash -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  dev-db-data:
