# Generated by Django 4.2.7 on 2023-12-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_created_on_course_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images', verbose_name='Main Image'),
        ),
    ]
