# Generated by Django 4.2.7 on 2023-12-08 05:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255, verbose_name='Lesson Title')),
                ('video', models.FileField(upload_to='course_lessons', validators=[django.core.validators.FileExtensionValidator(['.mp4', '.webm', '.mkv', '.flv'])], verbose_name='Lesson Title')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Course Lesson')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
