# Generated by Django 4.2.7 on 2023-12-08 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(upload_to='course_lessons', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mkv', 'flv'])], verbose_name='Lesson Title'),
        ),
    ]
