name: Test code
on: [push]

jobs:
  test-code:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check if docker workes without install
        run: docker ps


      - name: Build the docker image
        run: |
          docker build --tag django-image .

      - name: Test the docker image
        run: |
          docker run django-image pytest
